### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by nutinshell** [xjdrew/gotunnel#12]
大流量跑一段时间后崩溃了..

```
goroutine 177166 [semacquire]:
sync.runtime_Syncsemacquire(0xc820e68010)
	/usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc820e68000)
	/usr/local/go/src/sync/cond.go:62 +0x9b
github.com/xjdrew/gotunnel/tunnel.(*LinkBuffer).Pop(0xc820e68280, 0x0, 0x0, 0x0, 0x3)
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link_buffer.go:83 +0x1b6
github.com/xjdrew/gotunnel/tunnel.(*Link).pumpOut(0xc820e682c0)
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link.go:103 +0xb5
created by github.com/xjdrew/gotunnel/tunnel.(*Link).Pump
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link.go:131 +0xfe

goroutine 177128 [semacquire]:
sync.runtime_Semacquire(0xc82054cdb0)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82054cda4)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/xjdrew/gotunnel/tunnel.(*Link).Pump(0xc82054cd80, 0xc820026230)
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link.go:133 +0x11c
github.com/xjdrew/gotunnel/tunnel.(*Client).handleConn(0xc82000a240, 0xc8206ba160, 0xc820026230)
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/client.go:108 +0x2d9
created by github.com/xjdrew/gotunnel/tunnel.(*Client).listen
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/client.go:139 +0x520

goroutine 177129 [IO wait]:
net.runtime_pollWait(0x7f28b8c33120, 0x72, 0xc82000e1a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820697800, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820697800, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206977a0, 0xc83a29a000, 0x4000, 0x4000, 0x0, 0x7f28b8c2d050, 0xc82000e1a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026230, 0xc83a29a000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820c8def0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820c8def0, 0xc83a298000, 0x2000, 0x2000, 0x2000, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/xjdrew/gotunnel/tunnel.(*Link).pumpIn(0xc82054cd80)
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link.go:75 +0x183
created by github.com/xjdrew/gotunnel/tunnel.(*Link).Pump
	/root/gospace/src/github.com/xjdrew/gotunnel/tunnel/link.go:128 +0xb5
```

**Comment by xjdrew** [comment]
请问还有崩溃的更多堆栈？这些堆栈好像看不出来原因。
